export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM'
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM'
export const CHANGE_LOGGED_IN_STATUS = 'CHANGE_LOGGED_IN_STATUS'
export const RESET_AUTH_FROMS = 'RESET_AUTH_FORMS'

export const ERROR = 'ERROR'
export const SUCCESS = 'SUCCESS'
